### PR TITLE
Add Decision Cost Function metric

### PR DESCRIPTION
**Pull request by nryant**
Adds Decision Cost Function (DCF) metric used by NIST for evaluating SAD system output in OpenSAT.

### CODE REVIEW

**Comment by hbredin** [comment]
Thanks @nryant.

Would you mind mentioning this new metric in the documentation as well?

https://github.com/pyannote/pyannote-metrics/blob/69a7140fff51722a4cc3d1b422ca1bb21d94c801/docs/source/reference.rst#L38-L47

**Comment by nryant** [comment]
@hbredin , I updated the docs with a blurb about decision cost function. Let me know if that is satisfactory.

**Comment by hbredin** [comment]
That’s great! Thanks.

Will release a new version unless you have other contributions in the pipeline.

**Comment by hbredin** [comment]
Oh. One last question. Is it Decision or Detection Cost Function?

**Comment by nryant** [comment]
Ack. Should be Detection Cost Function. Thanks for the catch...guess I've spent too much time dealing with ROC curves recently. I've updated the pull request to reflect this.

**Comment by hbredin** [comment]
FYI, I just released v3.0, that includes this PR:

http://pyannote.github.io/pyannote-metrics/reference.html?highlight=detectioncostfunction#pyannote.metrics.detection.DetectionCostFunction

**Pull request merged**
