### PR TITLE
 Fixing pyannote-metrics.py for identification task, and fixing documentation references to pyannote-metrics.py script.

### PR DESCRIPTION
**Pull request by hadware**
- There was a small bug in the printing of identification error rate results that made the script crash.
- The script call example in the doc wasn't using the right name for the script.

Maybe (and just maybe) I could switch (in this PR)  the script to an endpoint to match the other pyannote commands? I find it a tad upsetting that this script is called with a `.py` (but it's not too bad, I still sleep well at night).

### CODE REVIEW

**Comment by hbredin** [comment]
Thanks. Please go ahead: make it an endpoint and remove this pesky `.py` 👍

**Comment by hadware** [comment]
image

**Comment by hadware** [comment]
This should be ready to merge.

**Comment by hbredin** [comment]
Thanks.

Can you please move `pyannote.metrics.applications.pyannote_metrics` to `pyannote.metrics.cli`? 

This will be coherent to upcoming `pyannote.database.cli`'s `pyannote-database` command.

**Comment by hadware** [comment]
I think eveything should be good now?

**Comment by hbredin** [comment]
🥳

**Comment by hbredin** [comment]
FYI, I just released v3.0, that includes this PR:

http://pyannote.github.io/pyannote-metrics/cli.html#command-line-tool

**Comment by hadware** [comment]
Nice! now I can only wait for fame and glory.

**Pull request merged**
